FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    bash \
    build-essential \
    stow \
    curl \
    git \
    locales \
    neovim \
    && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
    && locale-gen \
    && rm -rf /var/lib/apt/lists/*

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

RUN curl -sL https://taskfile.dev/install.sh | sh -s -- -d -b /usr/local/bin
